apiVersion: v1
kind: Pod
metadata:
  name: sample-imagepull
  namespace: default
  labels:
    app: sample-imagepull
spec:
  restartPolicy: Always
  containers:
    - name: app
      image: nonexistent.registry.example/this-image-does-not-exist:invalid
